export const listw = [
    {
        "id": 23456,
        "name": "Wallenbergsyndromet",
        "url": "http://googe.com",
        "entrytext_synonym": "Arteria cerebelli inferior posterior",
        "entrytext_subheadline": "Hjärnartär, nedre bakre lillhjärnsartären, PICA, Lillhjärnsartär, nedre bakre, Wallenbergsyndromet",
        "entrytext_main": "<div class=\"description\">Den nedre bakre lillhjärnsartären avges, en på hö. och en på vä. sida, från <a href=\"structure_163\" title=\"Arteria vertebralis\">kotartären</a> när denna kommit in i kraniehålan och just före det att de båda sidornas kotartärer förenas till den mittställda <a href=\"structure_67\" title=\"Arteria basilaris\">basartären</a>. I medicinska sammanhang används ibland förkortningen \"<strong>PICA</strong>\" (taget från engelskans språkbruk <strong>P</strong>osterior <strong>I</strong>nferior <strong>C</strong>erebellar <strong>A</strong>rtery). Artären försörjer delar av lilla hjärnan och av hjärnstammen. Vid stroke som drabbar PICA fås en skadebild som kallas för \"Wallenbergsyndromet\".<br><br><br>Wallenbergsyndromet innebär, i det typiska fallet, att den drabbade blir yr, starkt illamående, kräks, flackar okontrollerat med blicken (nystagmus), tappar balansen och faller omkull åt den sida där skadan sitter. Samtidigt försämras smärt- och temperaturkänsligheten i ansiktet på skadesidan och över resten av kroppen på motsatta sidan.</div>",
        "relatedlinks": "<ul>    <li><a href=\"structure_723\">Korta hjärnstamsomslutande artärer</a></li>  </ul>"
    },
    {
        "id": 34567,
        "name": "Wernickes fält",
        "url": "http://googe.com",
        "entrytext_subheadline": "Wernickes fält",
        "entrytext_main": "<div class=\"description\">Sensoriska talcentrum eller Wernikes fält är beläget i vä hemisfär och motsvarar bakre delen av <a href=\"structure_26\" title=\"Wernickes fält\">BA 22</a> tillsammans med <a href=\"structure_303\" title=\"Planum temporale\">tinninglobsplattan (planum temporale</a>) i tinningloben samt angränsande delar av  <a href=\"structure_42\" title=\"BA 39\">BA 39</a> (gyrus angularis) i hjässloben.  Området är ihopkopplat med motoriska talcentrum genom en associations-bana, 'bågen', (fasciculus arcuatus). <br> <br>Sensoriska talcentrum väljer de ord som på bästa sätt kan klä en tanke i rätt språkdräkt (tal och skrift). Sensoriska talcentrum ordnar dessa ord till  'mönstret'  för en begriplig och välstrukturerad mening. Här gäller den klassiska utsagan: 'En mening är en i ord klädd tanke'. <br><br>Sensoriska talcentrum är också den del av vår hjärna som ger språkljuden (fonemen), så som de når oss i form av tilltal, och språkljudens omformning i skrift (grafemen), en begriplig innebörd. <br><br>Litet tillspetsat och förgrovat kan man ge följande beskrivning av hur den talade språkdräkten blir till, hur den 'sys ihop' i vårt centrala nervsystem.<br><br>'Mönstret' till språkdräkten konstrueras (ritas upp) i sensoriska talcentrum. <br><br>'Mönstret' levereras sedan, via den bågformade associationsbanan (fasciculus arcuatus), till motoriska  talcentrum. <br><br>Här 'ritas mönstret över på talspråktyget'. <br><br>'Talspråktyget med uppritat mönster' sänds till SM I, <br><br>SM I 'skär till' ('klipper ut')  talspråktygets olika delar och levererar, via pyramidala bansystemen i samverkan med basala ganglierna och lilla hjärnan, delarna till, för talbildningen, lämpliga motorneurongrupper i hjärnstam och ryggmärg.<br><br>Motorneurongrupperna samarbetar och syr ihop  de enskilda  språkstyckena till den  färdiga språkdräkten,  i form av talade meningar, kommandes ut ur munnen och något litet även ur näsan.<br><br>En stor mängd muskler måste fås att samverka för att vårt tal skall bli tydligt och urskiljbart. Det handlar om   muskler som reglerar trycket i våra kroppshålor, om halsmuskler, struphuvudets muskler, svalgets muskler, tungans muskler och muskler som bildar väggar i munhålan (gom, läppar och kinder), i allt ett knappt hundratal enskilda muskler.<br><br>En skada på Wernickes fält (delar av Brodmannareorna 22 och 39 i vänster hemisfär) ger upphov till s.k. sensorisk talförlamning (sensorisk afasi, Wernickes afasi). En person som drabbats av sensorisk afasi talar flytande men orden och ordens betydelse blandas ofta huller om buller till en absurd och befängd, ofta obegriplig, s.k. 'ordsallad'. Den drabbade förstår inte talat språk, kan inte skriva, har svårt att förstå innehållet i en text samt klarar inte av att upprepa en kortare uppläst mening (dålig repetitionsförmåga).<br></div>",
        "relatedlinks": "<ul>    <li><a href=\"structure_42\">Area 39</a></li>    <li><a href=\"structure_46\">Area 44 (Motoriskt talcentrum)</a></li>    <li><a href=\"structure_51\">Associationsbana; bågformad</a></li>    <li><a href=\"structure_300\">Tinningloben</a></li>    <li><a href=\"structure_1347\">Yttersta nervtrådskapseln </a></li>  </ul>"
    },
    {
        "id": 45678,
        "name": "Working memory",
        "url": "http://googe.com",
        "entrytext_subheadline": "Korttidsminne, Arbetsminne, Working memory, Långtidsminne, Explicita/deklarativa minnen., Semantiskt minne., Episodiskt minne., Implicita/procedur/icke-deklarativa minnen.",
        "entrytext_main": "<div class=\"description\">När det gäller minnesbildning och minneslagring har intresset riktats mot <a href=\"structure_300\" title=\"Lobus temporalis\">tinningloben</a> (temporalloben) och då särskilt mot dess <a href=\"structure_584\" title=\"Temporallobens mesiala del\">inre</a> (mesiala) del. <br><br>Man talar om 1) korttidsminne och/eller <strong>arbetsminne (eng. working memory)</strong> och om 2) långtidsminne.<br><br>1) Korttidsminnet använder vi oss av ständigt och jämt. Det påminner oss om \"var vi befinner oss\" och inte minst var vi befann oss under de just förflutna tidsögonblicken, \"vad vi håller på med\" och höll på med under de just förflutna tidsögonblicken samt för planeringen av våra aktiviteter under nästa tidsögonblick. Man skulle kunna tala om en fortlöpande updatering av vårt medvetande mot bakgrund av det nyss inträffade; något som är helt avgörande för ett rationellt och begripligt beteende.<br><br>Korttidsminnen/arbetsminnen bildas hela tiden och glöms sedan bort inom loppet av  några sekunder / några minuter. <a href=\"structure_235\" title=\"Lobus frontalis\">Pannloberna</a> i samarbete med <a href=\"structure_137\" title=\"Lobus parietalis\">hjässloberna</a> förefaller att vara särskilt betydelsefulla för ett väl fungerande korttidsminne.<br><br>Typiska exempel på arbetsminnen är följande. <br>Man slår upp ett telefonnummer i telefonkatalogen, ögnar över det, \"stoppar in\" det i korttidsminnet, slår igen katalogen, knappar in numret, hoppas på svar, väntar och under tiden \"dunstar numret bort ur huvudet\".<br>Eller man skall ut och resa och måste packa sin väska. Man går i minnet(långtidsminnet) igenom vad som kan tänkas hända under resan och skapar i sitt korttidsminne en lista över saker som skall packas och i vilken ordning de skall plockas fram och läggas ner. Listan hålls sedan aktiv i korttids-minnet fram till att packningen är klar.<br><br>2) Långtidsminne. Man brukar tala om två huvudtyper av långtidsminnen. <br><br>a) Explicita eller deklarativa minnen. Här är vi klart medvetna om att vi minns och vi kan viljemässigt \"plocka fram\" olika faktaenheter (semantiskt minne): \"Göteborg ligger på västkusten.   Javisst, det där är en barnvagn.\" och välja ut samt styra olika minnesscener (episodiskt minne): \" Nu när jag tänker efter minns jag tydligt hur vi gick ner till roddbåten och Lillan ......\".<br><br>b) Implicita minnen eller procedurminnen. Här handlar det inte om att medvetet \"plocka upp\" en minnesbild, utan om att man omedvetet genomför ett tidigare inlärt/intränat beteende, ofta ett komplext rörelseprogram som utförs med ledning av de just aktuella sinnesintrycken och det planerade fortsatta beteendet (perseptuo-motoriskt minne). Så till exempel kan man med hjälp av ett batteri implicita minnen t.ex. cykla, knyta sina skosnören, hantera matbesticken, forma bokstäver, etc.<br></div>",
        "relatedlinks": "<ul>    <li><a href=\"structure_47\">Area 46</a></li>    <li><a href=\"structure_56\">Astrocyt</a></li>    <li><a href=\"structure_382\">Prefrontala hjärnbarken</a></li>    <li><a href=\"structure_631\">Kognitiv</a></li>    <li><a href=\"structure_738\">Glömska</a></li>    <li><a href=\"structure_1205\">Retikulära tegmentala ponskärnan</a></li>    <li><a href=\"structure_1410\">Ventrala tegmentkärnan</a></li>    <li><a href=\"structure_1392\">Inre vårtkroppskärnan</a></li>    <li><a href=\"structure_1414\">Yttre vårtkroppskärnan</a></li>    <li><a href=\"structure_1456\">Associativa/kognitiva återkopplingskretsen genom basala ganglierna.</a></li>  </ul>"
    }
];

export default listw;
